title: "Blog BlueCat & CCNA"
description: "Documentación y aprendizaje en redes, BlueCat y CCNA"
baseurl: ""
url: "https://wilberquinto455.github.io"
theme: minima

# Menú
navbar:
  - name: "Inicio"
    link: "/"
  - name: "BlueCat"
    link: "/pages/bluecat"
  - name: "CCNA"
    link: "/pages/ccna"
  - name: "Acerca de"
    link: "/about"
  - name: "Contacto"
    link: "/contact"    
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"   
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .gitattributes
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - .github
  - .vscode
  - .idea
  - .DS_Store
  - CNAME   
  - .jekyll-cache
  - .jekyll-metadata      
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo   
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    line_numbers: false
    span: false
    inline_theme: null
    line_number_start: 1
    line_number_padding: 4
    line_number_offset: 0 
    wrap: false 
    coderay_css: style  
  guess_lang: false 
  show_warnings: false  
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:          
    css_class: 'highlight'
    line_numbers: false
    span: false
    inline_theme: null
    line_number_start: 1
    line_number_padding: 4
    line_number_offset: 0 
    wrap: false 
    coderay_css: style  
  guess_lang: false 
  show_warnings: false  
  footnote_nr: 1